# Generated by Django 3.2.7 on 2021-10-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.TextField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('referencia', models.CharField(max_length=40)),
                ('nit_e', models.CharField(max_length=21)),
                ('nit_r', models.CharField(max_length=21)),
                ('_valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
